### ISSUE TITLE
minor mistake in the api docs

### ISSUE THREAD

**Issue by TheEt1234** [OgelGames/fakelib#3]
![image](https://github.com/user-attachments/assets/d0b28208-6c09-44f4-b9d0-d333c5954b42)

**Comment by TheEt1234** [comment]
(precisely here - https://github.com/OgelGames/fakelib/blob/master/API.md?plain=1#L62)

**Comment by OgelGames** [comment]
And another one here https://github.com/OgelGames/fakelib/blob/master/API.md?plain=1#L70

**Comment by OgelGames** [comment]
https://github.com/OgelGames/fakelib/commit/26580085f3bd65d0b66c36aa10a46582bd9d9535
